### ISSUE TITLE
helper_functions.h:63:34: error: 'M_PI' was not declared in this scope in windows.

### ISSUE THREAD

**Issue by sookinoby** [udacity/CarND-Kidnapped-Vehicle-Project#10]
In windows the math.h does not define the constant M_PI. So we get an error as M_PI was not declared in the scope in windows.
To fix this add 

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

helper_functions.h file

**Comment by Mahmoodsalah** [comment]
What is the best place to put it inside helper_function.h

**Comment by baumanab** [comment]
Sorry for the technical issue. The code has been updated to resolve.
