### ISSUE TITLE
install-ubuntu.sh execute error

### ISSUE THREAD

**Issue by Cretheego** [udacity/CarND-Kidnapped-Vehicle-Project#19]
When I intall uWebSocketIO in ubuntu by execute install-ubuntu.sh, I encouter a error:

> CarND-Kidnapped-Vehicle-Project-master/CarND-Kidnapped-Vehicle-Project-master/src/main.cpp:1:21: fatal error: uWS/uWS.h: No such file or directory

where is this  file or directory?

**Comment by sheepwxy** [comment]
> re is this

hello,how did you solve the problem?
