### ISSUE TITLE
Using GPS uncertainty for prediction step

### ISSUE THREAD

**Issue by amakurin** [udacity/CarND-Kidnapped-Vehicle-Project#26]
main.cpp
...
36 double sigma_pos [3] = {0.3, 0.3, 0.01}; // GPS measurement uncertainty [x [m], y [m], theta [rad]]
...
82 pf.prediction(delta_t, sigma_pos, previous_velocity, previous_yawrate);

Although it will work as is, using GPS uncertainty on prediction step is confusing and bad for understanding of whole process. For prediction step, velocity and yaw rate uncertainties should be used.

**Comment by baumanab** [comment]
Sorry for the confusion. Hopefully this will make more sense after reading the discussion in the last need thread. 

https://discussions.udacity.com/t/sigma-pos-and-gps-measurement-uncertainty/504139/2
