### ISSUE TITLE
Contradicting instructions.

### ISSUE THREAD

**Issue by fazzolini** [udacity/CarND-Kidnapped-Vehicle-Project#30]
In README it is not entirely clear which files should a student modify.

Here it implies you should only touch `particle_filter.cpp`:
`All you will submit is your completed version of particle_filter.cpp, which is located in the src directory.`

Here it says you can actually change `main.cpp`:
`The program main.cpp has already been filled out, but feel free to modify it.`

Over here it says you can modify both `.cpp` and `.h` files for the filter:
`Note that the programs that need to be written to accomplish the project are src/particle_filter.cpp, and particle_filter.h`

In addition, project rubric does not specify that you can only change the `.cpp` file. 

I am at this project now, and some methods require too much processing and I think it would be much better design to introduce additional methods in the header file to make functionality more modular, but I am afraid the project would not pass if I do so. Please clarify.

**Comment by mvirgo** [comment]
Good call! I have changed this through e498ea9 (finally) so that it is less confusing.
