### ISSUE TITLE
fatal error: 'openssl/opensslv.h' file not found

### ISSUE THREAD

**Issue by GiffinOsborne** [udacity/CarND-Kidnapped-Vehicle-Project#48]
Hi, I was trying to start work on the project from my Mac but I am having issues with the install-mac.sh file. It had issues from line 5 which I resolved due to someones comment on an earlier issue. Now however, Im having issues with it not being able to find openssl/opensslv.h any guidance would be appreciated

Thanks in advance

Full log:

Updating Homebrew...
Warning: openssl@1.1 1.1.1g is already installed and up-to-date
To reinstall 1.1.1g, run `brew reinstall openssl@1.1`
Warning: libuv 1.38.1 is already installed and up-to-date
To reinstall 1.38.1, run `brew reinstall libuv`
Warning: cmake 3.18.0 is already installed and up-to-date
To reinstall 3.18.0, run `brew reinstall cmake`
Cloning into 'uWebSockets'...
remote: Enumerating objects: 106, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 7289 (delta 58), reused 54 (delta 26), pack-reused 7183
Receiving objects: 100% (7289/7289), 3.29 MiB | 147.00 KiB/s, done.
Resolving deltas: 100% (4848/4848), done.
Note: switching to 'e94b6e1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at e94b6e1 Node.js: add getResponsePrototype, getRequestPrototype again
patching file CMakeLists.txt
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/local/Cellar/openssl@1.1/1.1.1d/lib/libcrypto.dylib   
-- Found ZLIB: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libz.tbd (found version "1.2.11") 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/giffinosborne/CLionProjects/CarND-Kidnapped-Vehicle-Project/uWebSockets/build
Scanning dependencies of target uWS
[  6%] Building CXX object CMakeFiles/uWS.dir/src/Extensions.cpp.o
[ 13%] Building CXX object CMakeFiles/uWS.dir/src/Group.cpp.o
In file included from /Users/giffinosborne/CLionProjects/CarND-Kidnapped-Vehicle-Project/uWebSockets/src/Group.cpp:1:
In file included from /Users/giffinosborne/CLionProjects/CarND-Kidnapped-Vehicle-Project/uWebSockets/src/Group.h:4:
In file included from /Users/giffinosborne/CLionProjects/CarND-Kidnapped-Vehicle-Project/uWebSockets/src/WebSocket.h:4:
In file included from /Users/giffinosborne/CLionProjects/CarND-Kidnapped-Vehicle-Project/uWebSockets/src/WebSocketProtocol.h:5:
/Users/giffinosborne/CLionProjects/CarND-Kidnapped-Vehicle-Project/uWebSockets/src/Networking.h:4:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/uWS.dir/src/Group.cpp.o] Error 1
make[1]: *** [CMakeFiles/uWS.dir/all] Error 2
make: *** [all] Error 2
[  6%] Building CXX object CMakeFiles/uWS.dir/src/Group.cpp.o
In file included from /Users/giffinosborne/CLionProjects/CarND-Kidnapped-Vehicle-Project/uWebSockets/src/Group.cpp:1:
In file included from /Users/giffinosborne/CLionProjects/CarND-Kidnapped-Vehicle-Project/uWebSockets/src/Group.h:4:
In file included from /Users/giffinosborne/CLionProjects/CarND-Kidnapped-Vehicle-Project/uWebSockets/src/WebSocket.h:4:
In file included from /Users/giffinosborne/CLionProjects/CarND-Kidnapped-Vehicle-Project/uWebSockets/src/WebSocketProtocol.h:5:
/Users/giffinosborne/CLionProjects/CarND-Kidnapped-Vehicle-Project/uWebSockets/src/Networking.h:4:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>

**Comment by UAnjali** [comment]
Hi @GiffinOsborne,
Though we are a little late in responding. We suggest you visit [this](https://github.com/udacity/CarND-Kidnapped-Vehicle-Project/issues/11) issue if the problem still persists.
Thanks
