### ISSUE TITLE
Invalid hyperlink in Readme

### ISSUE THREAD

**Issue by gabesj** [udacity/CarND-Kidnapped-Vehicle-Project#49]
The Readme has the following line:
"Tips for setting up your environment can be found here"
And the word "here" is a link to the website https://classroom.udacity.com/nanodegrees/nd013/parts/40f38239-66b6-46ec-ae68-03afd8a601c8/modules/0949fca6-b379-42af-a919-ee50aa304e6a/lessons/f758c44c-5e40-4e01-93b5-1a82aa4e044f/concepts/23d376c7-0195-4276-bdf0-e02f1f3c665d
But that page no longer exists.

**Comment by UAnjali** [comment]
Hi @gabesj,
Though we are late to respond, we have updated the file based on your suggestion. 
Thank you
