### ISSUE TITLE
prediction function comment may be confusing

### ISSUE THREAD

**Issue by tzhaojustdoit** [udacity/CarND-Kidnapped-Vehicle-Project#50]
In particle_filter.cpp line 37:
`void ParticleFilter::prediction(double delta_t, double std_pos[], 
                                double velocity, double yaw_rate) {
  /**
   * TODO: Add measurements to each particle and add random Gaussian noise.
   * NOTE: When adding noise you may find std::normal_distribution 
   *   and std::default_random_engine useful.
   *  http://en.cppreference.com/w/cpp/numeric/random/normal_distribution
   *  http://www.cplusplus.com/reference/random/default_random_engine/
   */

}`
Could "Add measurements" be "Add movement"?

**Comment by UAnjali** [comment]
Hi @tzhaojustdoit,
Though we are a little late to respond, may be this can help you:
   * @param delta_t Time between time step t and t+1 in measurements [s]
   * @param std_pos[] Array of dimension 3 [standard deviation of x [m], standard deviation of y [m], standard deviation of yaw [rad]]
   * @param velocity Velocity of car from t to t+1 [m/s]
   * @param yaw_rate Yaw rate of car from t to t+1 [rad/s]
Although, feel free to suggest an update to the starter code. 
Happy Learning
Udacity
