### ISSUE TITLE
Incorrect comment on updateWeights

### ISSUE THREAD

**Issue by mithi** [udacity/CarND-Kidnapped-Vehicle-Project#9]
in the `updateWeights` function it says:
```
//   Note that you'll need to switch the minus sign in that equation to a plus to account
//   for the fact that the map's y-axis actually points downwards.
```
It is agreed that
> That comment is incorrect, you shouldn’t change the sign. they still haven’t fixed it.

Discussion from: https://carnd.slack.com/archives/C4TSP7BFU/p1494255995984903

**Comment by beeva-ricardoguerrero** [comment]
This issue seems to be already solved.

**Comment by mithi** [comment]
@beeva-ricardoguerrero  Thanks!
